filebeat.inputs:
  - type: container
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata: ~
      - decode_json_fields:
          fields: ["message"]
          target: "json"
          overwrite_keys: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "TdptwLko5fGX6THYSnMtHFUSh0SYltT/pncvdxjyj60g="

setup.kibana:
  host: "http://kibana:5601"

logging:
  level: debug
  to_event: true
  selectors: ["*"]
