services:
  filebeat:
    image: elastic/filebeat:8.15.3
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./nginx/logs:/usr/share/nginx/logs:ro
    networks:
      - elastic_network
      - webnet
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 1

networks:
  elastic_network:
    external: true
  webnet:
    external: true
