filebeat.modules:
  - module: nginx
    access:
      enabled: true
      var.paths: ["/usr/share/nginx/logs/access.log*"]
    error:
      enabled: true
      var.paths: ["/usr/share/nginx/logs/error.log*"]

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "TdptwLko5fGX6THYSnMtHFUSh0SYltT/pncvdxjyj60g="

setup.template.enabled: true
setup.template.overwrite: true

logging.level: debug
logging.to_files: true
logging.files:
  path: /usr/share/filebeat/logs
  name: filebeat
  keepfiles: 7
  permissions: 0644
