version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/var/www/html
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      sh -c "
      certbot certonly --webroot --webroot-path=/var/www/certbot
      --email josenerydev@gmail.com --agree-tos --no-eff-email
      -d apache.dotnery.com && sleep 90
      "
