services:
  web:
    image: app:1.0.2
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    networks:
      - webnet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  webnet:
    external: true
