services:
  web:
    image: app:1.0.7
    volumes:
      - ./logs:/var/log/apache2
    networks:
      - webnet
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

networks:
  webnet:
    external: true
