services:
  web:
    image: app:2.0.1
    networks:
      - webnet
      - elastic_network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "host.docker.internal:24224"
        tag: "apache"
        fluentd-async: "true"
    deploy:
      replicas: 3

networks:
  webnet:
    external: true
  elastic_network:
    external: true
