worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format json_logs '{'
                        '"remote_addr": "$remote_addr",'
                        '"remote_user": "$remote_user",'
                        '"time_local": "$time_local",'
                        '"request": "$request",'
                        '"status": "$status",'
                        '"body_bytes_sent": "$body_bytes_sent",'
                        '"http_referer": "$http_referer",'
                        '"http_user_agent": "$http_user_agent",'
                        '"http_x_forwarded_for": "$http_x_forwarded_for"'
                        '}';
    access_log /dev/stdout json_logs;
    error_log /dev/stderr warn;

    include /etc/nginx/conf.d/*.conf;
}
