version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - webnet
      - elastic_network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "host.docker.internal:24224"
        tag: "nginx.container"
    deploy:
      mode: global

networks:
  webnet:
    external: true
  elastic_network:
    external: true
